name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci

      - name: Replace environment variables
        run: |
          sed -i 's|__AUTH_URL__|${{ secrets.SUPABASE_URL }}|g' src/environments/environment.prod.ts
          sed -i 's|__AUTH_KEY__|${{ secrets.SUPABASE_KEY }}|g' src/environments/environment.prod.ts
          sed -i 's|__API_KEY__|${{ secrets.API_KEY_ADMIN }}|g' src/environments/environment.prod.ts
      - name: Build Angular App
        run: npx ng build --configuration=production

      - name: Copy routing config to output folder
        run: cp staticwebapp.config.json dist/sdp-angular-app/browser/

      - name: List build output (debugging)
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of dist/sdp-angular-app directory:"
          ls -la dist/sdp-angular-app/
          echo "Contents of dist/sdp-angular-app/browser directory:"
          ls -la dist/sdp-angular-app/browser/

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_COAST_007353203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "dist/sdp-angular-app/browser"

  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Replace environment variables
        run: |
          sed -i 's|__AUTH_URL__|${{ secrets.SUPABASE_URL }}|g' src/environments/environment.prod.ts
          sed -i 's|__AUTH_KEY__|${{ secrets.SUPABASE_KEY }}|g' src/environments/environment.prod.ts
          sed -i 's|__API_KEY__|${{ secrets.API_KEY_ADMIN }}|g' src/environments/environment.prod.ts

      - name: Run tests
        run: npm run test:ci

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report # The name of the artifact to be downloaded
          path: coverage/       # The path to the folder to upload

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: software-design-project-2025/sdp-frontend

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_COAST_007353203 }}
          action: "close"
          app_location: "/"
